env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - standard
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules: {"react/no-unescaped-entities": 0}
settings:
  {
    react: 
    {
      version: detect
    }
  }
